lightonai/pylate

- pylate/models/Dense.py
- pylate/models/colbert.py
- setup.py
This PR solves some of the issues related to model loading.
First, it removes the model_kwargs `add_pooling_layer` that prevented the instantiation of a pooler within BERT models but is not common across all encoders (see #51).
I considered removing the pooler after initialization, but then the saved PyLate model does not have weights for it and it yields a warning saying that those weights are not properly loaded from checkpoint. Although it does not matter as we are not using it anyways, this message can be misleading. Thus, I choose to let it be, as we are using the sequence_embeddings and not the pooled output, it's a small additional useless computation but I did not find a better solution.
Second, it adds a function to support loading a model created using the stanford-nlp library. …
> Loading logic rework

- docs/documentation/.pages
- docs/documentation/fastapi.md
- docs/documentation/server.md
- pylate/server/README.md
- pylate/server/server.py
- pytest.ini
- setup.py
This PR adds code to serve the embeddings of a ColBERT model using FastAPI, leveraging [batched](https://github.com/mixedbread-ai/batched) to create dynamic batches.
See the README for details about how it works
> Adding a FastAPI server

- pylate/models/colbert.py
When experimenting around, I realized that some models do not have "architectures" in their config (e.g, [debertav3](https://huggingface.co/microsoft/deberta-v3-base).
This PR just check if there is one before checking if it is a HF_ColBERT (and thus that the model is a stanford-nlp model).
> Check if architectures is in the config before reading it

- pylate/utils/processing.py
This MR update the knowledge distillation processing to make it compatible with DictDataset and Dataset. While the previous typing showed that this module take as input Dataset, it does not. It takes only as input DictDataset. Make this module compatible with both DictDataset and Dataset. Enable also the user to define the split which is defined to "train" by default just like the previous version.
> Make knowledge distillation processing compatible with DictDataset and Dataset.

- pylate/models/colbert.py
- setup.py
This PR fixes a compatibility issue introduced in ST 3.1 in [this commit](https://github.com/UKPLab/sentence-transformers/commit/6257cb00ef87ddc8f445f0e436377ea4c48879b2).
Basically, this added the possibility add module_kwargs in the config so that the model can leverage them for a specific processing, such as the dataset_embeddings of [cde](https://huggingface.co/jxm/cde-small-v1).
This fix allows to bump the version of ST to newer ones and also to handle such custom processing aswell (as we are extending the ST model).
Edit for more information: the [load_sbert_model function set the self.modules_kwargs](https://github.com/UKPLab/sentence-transformers/blob/a4be00f3fcb635f536566044d40c41513a495818/sentence_transformers/SentenceTransformer.py#L306) that are then used in the [forward pass …
> Fixing issue with ST 3.1 and bumping version

- pylate/models/Dense.py
- setup.py
#68 fixed the local loading of Stanford models, but the issue is that the safe tensor is only created when uploaded to HF through the dedicated bot.
This PR changes the loading logic to rely on the `pytorch_model.bin` file that is always there both locally and remotely.
cc @jessiejuachon
> Stanford loading using bin file

- pylate/models/Dense.py
- tests/test_model.py
#69 actually broke the loading of recent stanford-nlp models (small/jina), as they do not have bin.
That is on me, I checked the colbertv2 repository that had both safe tensor AND bin and rushed to the conclusion that all of them had both.
This PR merge old safe tensor loading and the new bin loading to be able to load both type of repository.
We first try to load safe tensors and fall back to bin if not existing.
Also added some tests for loading different types of models (base, ST base, stanford-nlp bin/safetensor and PyLate), as well as a small check that should make sure that the model is not only loaded but correctly loaded.
> Add safetensor OR bin loading logic + add loading tests

- docs/documentation/training.md
- pylate/losses/distillation.py
This PR change the default of normalize_scores to False and add documentation about the parameters.
The rationale behind this change is two-fold:
1. The setup is not really common for the large audience and [the user can be surprised by the loss magnitude](https://github.com/lightonai/pylate/discussions/58). Also, if the user use his own dataset without normalizing the teacher scores, it could be hurting the performance.
2. [JinaColBERT-v2 had mitigated results using normalization](https://arxiv.org/pdf/2408.16672), so I am not sure it is worth it to make it the default.
Before merging, there is two things that needs to be discussed:
1. The datasets we have released have normalized scores, which could make the boilerplate a bit off.
2. When building the functionality, I decoupled the …
> [Draft] Setting normalize_scores default to False

- pylate/models/colbert.py
Right now, we are using default values for doc/query length, markers and attending to expansion tokens when reading stanford models.
This causes some issues as highlighted in #85 and also requires the user to specify a lot of information when using a model that is not using default values, as can be seen with the [loading of Jina-ColBERT.](https://lightonai.github.io/pylate/models/models/#available-models)
This PR simply add the reading process of the `artifact.metadata` file of Stanford NLP models and read markers, lengths and attend to expansion tokens values.
As usual, we override those if the user feed values to the init of the model. Also changed the `attend_to_expansion_tokens` parameter to match the other (None by default and override at the end).
> Read stanford configs

- pylate/__version__.py
- Addition of NanoBEIREvaluator, allowing to give quick signal about the learning during training
Support of Python 3.9
- Bump of transformers/ST versions, allowing to use ModernBERT in PyLate and also fixing an issue for loading models after training them with trust_remote_code=True
- Reading of Stanford-NLP models configurations (markers, attending to expansion tokens, ...), allowing to load models such as Jina-ColBERT without having to specify all these parameters
Some fixes
> Bump version 1.1.5

- pylate/models/colbert.py
@raphaelsty @NohTow 
I believe this is an urgent fix that also requires a new release.  
```python
from pylate import models
model = models.ColBERT(
model_name_or_path="colbert-ir/colbertv2.0",
)
```
```
No sentence-transformers model found with name colbert-ir/colbertv2.0.
Traceback (most recent call last):
File "/Users/A200009373/Documents/Coding/pylate/test.py", line 7, in <module>
model = models.ColBERT(
^^^^^^^^^^^^^^^
File "/Users/A200009373/Documents/Coding/pylate/pylate/models/colbert.py", line 283, in __init__
self.query_prefix = metadata["query_token_id"]
~~~~~~~~^^^^^^^^^^^^^^^^^^
KeyError: 'query_token_id'
```
> fix:  Loading Model - Stanford Models

- Makefile
- pylate/models/colbert.py
This PR allows the use of push_to_hub with the PyLate template. 
ST lib is importing its own create ModelCard function that is not getting overwritten by PyLate. 
```
from pylate import models
from pylate.models.colbert import PylateModelCardData
model = models.ColBERT(
model_name_or_path="colbert-ir/colbertv2.0",
model_card_data=PylateModelCardData(model_name="GerColBERT2"),
)
model.push_to_hub(".....", private=True,  exist_ok=True)
```
> fix: use model card from pylate for  upload to hub

- pylate/losses/__init__.py
- pylate/losses/cached_contrastive.py
- tests/test_cached_contrastive.py
This PR adds CachedContrastive loss to the available loss.
As described in the [paper](https://arxiv.org/pdf/2101.06983), this effectively allows to scale the batch size of contrastive loss without requiring more memory (at the cost of a slightly slower training) by decomposing the loss computation into representations computation without the gradient to compute similarities over the whole batch and then computing the gradients on sub batches.
The code is vastly copied from sentence-transformers implementation (thanks @tomaarsen), one of the main difference being the chunking of the score computation as well (as MaxSim is pretty memory intensive for very large batches).
> Adding GradCache (cached contrastive loss)

- pylate/losses/cached_contrastive.py
- pylate/losses/contrastive.py
- pylate/utils/__init__.py
- pylate/utils/distributed.py
This PR adds the option to gather documents from the other GPUs in both contrastive and cached contrastive loss.
The default is still not to gather even though in my opinion it should be the default for back-compatibility purpose.
Also, this is most likely bringing the most improvement when all the GPUs have batches from the same dataset in the multi dataset setting. 
I am having discussion with @tomaarsen to define what is the best way to include this option into ST, but for now I have found a workaround and will add a boilerplate later.
The sanity check I ran on a ms marco dataset:
- GradCache is almost equivalent to standard contrastive for the same bs (Not == because I cannot seed everything into ST)
- Increasing the global batch size with grad cache while using the old batch size as …
> Add gathering to (cached) contrastive loss

- .github/workflows/linter.yml
- .github/workflows/python-tests.yml
- docs/api/indexes/Voyager.md
- docs/api/losses/Contrastive.md
- docs/api/losses/Distillation.md
- docs/api/models/ColBERT.md
- docs/api/models/Dense.md
- docs/api/retrieve/ColBERT.md
- docs/api/utils/ColBERTCollator.md
- docs/api/utils/KDProcessing.md
- pylate/hf_hub/model_card.py
- pylate/losses/cached_contrastive.py
- pylate/models/colbert.py
- pylate/utils/distributed.py
- setup.py
- tests/test_contrastive.py
- tests/test_model.py
- tests/test_model_loading.py
- chor: st to 4.0.2
- fix: [cached_contrastive.py](https://github.com/lightonai/pylate/blob/2d094a724866d6e15701781528368438081c0157/pylate/losses/cached_contrastive.py#L29) https://github.com/lightonai/pylate/issues/106
- update model_card to use https://github.com/UKPLab/sentence-transformers/pull/3253
- linting
- ci: rerun test_load_model on fail
- ci: add cache to ci to reduce errors when loading files from hf
> st to 4.0.1 & lint & model_card & fix mps cached_contrastive

- pylate/losses/cached_contrastive.py
- pylate/losses/contrastive.py
- pylate/utils/__init__.py
- pylate/utils/distributed.py
Hello,
To compute contrastive loss with gathered elements from other GPUs, you have two solutions:
- Gather everything (queries + documents) _without the gradients in remote elements_. In this case, you need to compute the loss for all the elements on all the GPUs so every elements receive their full update on their local GPUs.
- Gather only the documents _with the gradients_. In this setup, the queries receive the full update because we gathered all the documents, but the documents receive the update w.r.t each query directly from the GPU holding those queries.
Please see [this](https://github.com/mlfoundations/open_clip/issues/616) for more information.
The former requires less communication (IIUC, a reduce_scatter operation during the backprop) while the latter is less memory intensive …
> Change the gathering versions to local losses with gradients

- pylate/losses/cached_contrastive.py
- pylate/losses/contrastive.py
- pylate/utils/__init__.py
- pylate/utils/distributed.py
With the recent addition of gathering from other gpus in a multi-gpu setting, there's a scaling by the world size missing to the loss (because PyTorch does an average over the number of GPUs by default, so we need to scale by the same number to have a similar loss no matter the number of GPUs).
Also took the opportunity to create a dedicated function for getting the rank instead of duplicating code.
I wonder if we should set the world size/rank as a parameter to only read it once instead of at each step... Maybe it's too much optimization idk
> Scale contrastive loss by world size

- pylate/losses/cached_contrastive.py
- pylate/losses/contrastive.py
Hey,
This PR adds a temperature parameter to the contrastive losses.
I initially removed it when copying the losses from ST because it is named "scale" and was actually a multiplicative scalar instead of being called temperature and dividing the similarities.
It turns out, for contrastive training, we require a very low temperature if we want to get the best performance possible.
I set the default to 1.0 to be equivalent to previous trainings, but maybe using 0.02 is better as it is the most commonly used value.
WDYT @raphaelsty?
> Add temperature parameter to contrastive losses

- pylate/indexes/plaid.py
- pylate/indexes/stanford_nlp/indexer.py
- pylate/indexes/voyager.py
- tests/test_plaid.py
This is #121 locally to extend the branch and add some tests.
Essentially, Voyager do not handle index loading from path on Windows (I suppose they do not added the case), but file-like loading is working and it seems to also work on Linux.
> Use file-like loading for the Voyager index to fix Windows loading (and add loading tests for indexes)

- pylate/hf_hub/model_card_template.md
In the current version, when a model card is generated, the `model id` of the new pylate model in the sample python code sections is not surrounded by quotation marks.
This causes an error whenever someone copies and tries to run the sample code
Example:
```python
model = models.ColBERT(
model_name_or_path=rasyosef/colbert-roberta-amharic-base,
)
```
Added double quotes around the model id in `model_card_template.md`
```
model = models.ColBERT(
model_name_or_path="{{ model_id | default('pylate_model_id', true) }}",
)
```
> fixed bug in model card template

- pyproject.toml
Hey,
This PR change the transformers requirement from a pinned version to a range, to allow use of PyLate with different setups (notably for RAGatouille). 
Also update the max version of transformers to allow the use of Qwen 3.
Related to #133 and #134
> transformers version range
